### ISSUE TITLE
Does Dax Studio 2.9.4 is windows 10 compatible ?

### ISSUE THREAD

**Issue by gvitalipro** [DaxStudio/DaxStudio#236]
**Is your feature request related to a problem? Please describe.**

Hello,

I can't find on the website if Dax Studio 2.9.4 is Windows 10 compatible/supported
Also I would like to find if Dax Studio is compatible with Office 2016/365 32/64bits
Do you know where I can find these informations ?

I find it's compatible with Excel 2010 and Excel 2013 but haven't find for other Excel versions

"As of version 2 there is now a single integrated installer which caters for both 32 and 64 bit installs and for both Excel 2010 and Excel 2013. It will also download and install any missing prerequisites."

Thank you,
Guillaume

**Describe the solution you'd like**

To have somewhere in the Dax Studio website a clear view of which version is Windows 10 compatible

**Describe alternatives you've considered**

**Additional context**

**Comment by dgosbell** [comment]
Yes, DAX Studio is supported on Win 10 and with Excel 2016 (both 32 & 64 bit). This is the primary configuration that we develop and test on.

It should also still work on Win 7 / Win 8 & Win 8.1 and Excel 2010 & Excel 2013. The main requirement for the operating system is that it supports the .Net Framework 4.7.1 or later (for this reason DAX Studio is not supported on Win XP or earlier)

I'll find a place to add this information to the website.

**Comment by gvitalipro** [comment]
Hello,

Thank you for your respond, look forward to see it on the website.

**Comment by teknowledgist** [comment]
The compatibility and dependencies are really not clear.

The [install documentation](https://daxstudio.org/documentation/installation/single-installer/) says it needs .NET 4.5, not 4.7.1.  Which should be installed?

Also, it mentions that it will download and install the SQL Server 2016 ADOMD and AMO.  If a machine is off-line, do those need to be downloaded and installed first?

Thanks.

**Comment by dgosbell** [comment]
Sorry, the docs are a little out of date. I just pushed a fix to update this information. We now **only** need .Net 4.7.1 

Microsoft has changed the way they deploy the other dependencies so these are now bundled into our installer.

**Comment by teknowledgist** [comment]
Great!  Thank you!

**Comment by JAPintor** [comment]
HI @dgosbell 
Until a few days ago My DAX Studio works fine (latest version 2.10.2). 
Now i can't get the result of this simple statment (even run DAX code still OK.)
but
**select * from $SYSTEM.DISCOVER_CALC_DEPENDENCY**
because it comes up with this error.
In portuguese -" Detetado nó de dependência não suportado"
In English - "Unsupported dependency node detected"
(PBI Desktop is also the latest version March 2020) - Versão: 2.79.5768.721 64-bit (março de 2020)
I didn't change my pbix models ( and i tested in several models and gives me the same error).
i didn't get his error only in a very simple one pbix, all the other gave me the error.
Do you have any idea why this start happens?
![DAX Studio Error](https://user-images.githubusercontent.com/29382089/77352078-84afd980-6d36-11ea-89b3-5ac4f89f59eb.JPG)

Thanks
José Pintor

**Comment by dgosbell** [comment]
@JAPintor - This looks like a completely different issue, unrelated to the Win 10 compatibility. And it looks like this error is coming back from the Power BI engine. I have the same version of desktop and cannot reproduce this issue. Do any of your measures have yellow warning triangles against them in Power BI Desktop? 

If you'd like me to investigate further I'd need to see the structure of your model. Are you able to either upload an example pbix file that exhibits this error to this issue? 

Or can you tick the following option in File > Options
![image](https://user-images.githubusercontent.com/8241830/77369524-f299e680-6db2-11ea-94e5-cd2986793bc5.png)
Then choose the "Export Metrics" option from the Advance tab and upload the .vpax file to this issue on Github?  (note: this will include table and column names and measure definitions in the vpax file but it will not include ANY rows from your tables, just their structure)

**Comment by JAPintor** [comment]
Hi @dgosbell,
Thanks for your time and great answer.
As far as i can see i don't have measures ou calculetd columns with errors.
I can attach a pbix sample file, with a few tables and measures / calculated columns whereas the problem persists.
If you can take a look at this pbix file, i'll appreciate.
If you want i can also prepare a file to you with DAX Studio for VertiPaq Analyzer, but with this pbix file i think you can analyze everething... 
Thanks again.
[Test GitHub.zip](https://github.com/DaxStudio/DaxStudio/files/4376816/Test.GitHub.zip)

Regards,
José Pintor

**Comment by JAPintor** [comment]
Hello Darren Gosbell,

Did you see my reply tio you in GitHub

Link pbix file; https://github.com/DaxStudio/DaxStudio/files/4376816/Test.GitHub.zip

 



Thanks for your time.

 

Regards,

Jos]e Pintor

 

De: Darren Gosbell <notifications@github.com> 
Enviada: 23 de março de 2020 23:41
Para: DaxStudio/DaxStudio <DaxStudio@noreply.github.com>
Cc: JAPintor <jose.a.pintor@sig360.pt>; Mention <mention@noreply.github.com>
Assunto: Re: [DaxStudio/DaxStudio] Does Dax Studio 2.9.4 is windows 10 compatible ? (#236)

 

@JAPintor <https://github.com/JAPintor>  - This looks like a completely different issue, unrelated to the Win 10 compatibility. And it looks like this error is coming back from the Power BI engine. I have the same version of desktop and cannot reproduce this issue. Do any of your measures have yellow warning triangles against them in Power BI Desktop?

If you'd like me to investigate further I'd need to see the structure of your model. Are you able to either upload an example pbix file that exhibits this error to this issue?

Or can you tick the following option in File > Options
 <https://user-images.githubusercontent.com/8241830/77369524-f299e680-6db2-11ea-94e5-cd2986793bc5.png> 
Then choose the "Export Metrics" option from the Advance tab and upload the .vpax file to this issue on Github? (note: this will include table and column names and measure definitions in the vpax file but it will not include ANY rows from your tables, just their structure)

**Comment by dgosbell** [comment]
Hi José, I did see your reply and I get the same error when I connect to your model with SQL Server Management Studio so this is not a DAX Studio specific error -  it's something in your model exposing what looks like a bug in the Power BI engine. I've tried changing a few things but have not been able to isolate this issue yet.

**Comment by JAPintor** [comment]
Ok Thanks for your time.
I look forward to hearing from you soon.

José Pintor

**Comment by marcosqlbi** [comment]
It seems a bug in the AS engine related to this really strange situation.
Your table “Idioma” loads the “Idioma (PTG)” parameter into a table.
Don’t ask me why… but this creates a strange situation. However, I don’t think it’s a good idea to load a PQ parameter as a table, just create a regular table in another query getting the value from the parameter and load that table in the model.
I suggest you submit the issue to Microsoft so they can work on a fix.
