### ISSUE TITLE
Tool is not turning up - Logo appears but application does not start

### ISSUE THREAD

**Issue by write2anees** [DaxStudio/DaxStudio#402]
Could You Please Help!!

When I launch the dax studio, the program logo appears, but application never starts up.

The Dax Studio Checker shows the following, What could be the problem?

    Version =  v2.12.2.344
    DaxStudio.exe Version =  v2.12.2.344

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Pro
    OSRelease       = 1607
    OSVersion       = 10.0.14393
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.89
    FreeMemoryGB    = 10.62

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.7.03062
    v4\Client\1033 -> 4.7.03062
    v4\Full -> 4.7.03062
    v4\Full\1033 -> 4.7.03062
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 461814 (4.7.2)
    PASS > .Net Version 4.7.2 is above the required minimum

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 21
    AMO : 19.6.0.0
    ADOMD : 19.6.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.12.2.344, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files (x86)\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1

Registry Settings
=======================

Thanks,

**Comment by dgosbell** [comment]
Everything looks fine with the checker report. Can you try starting DAX Studio with the [diagnostics logging on](https://daxstudio.org/documentation/troubleshooting/logging-settings/) and if that creates a log file can you upload it to this issue on Github? Have you tried running the portable version of DAX Studio and seeing if that works?

**Comment by write2anees** [comment]
Thanks for your response @dgosbell 

Please find log file attached, Yes, I have tried portal version of DAX Studio but no luck.

Thanks,
[DaxStudio-20200810.log](https://github.com/DaxStudio/DaxStudio/files/5052608/DaxStudio-20200810.log)

**Comment by write2anees** [comment]
Hello Gosbell,

Thanks for your response.  Please find the log file attached.

Yes, I have tried the portable version of DAX Studio but no luck.

I uploaded the log file to this issue on Github.

**Comment by write2anees** [comment]
Is anyone experiencing the same problem?

**Comment by dgosbell** [comment]
I've been through you log file and I've compared the log events to the start up process in the source code. So far everything looks like it should be working. The code is right at the point where it should display the user interface. 

Can you check the event viewer after trying to start DAX Studio and see if it captures anything? There was a rare bug with .Net in Windows 7 that would crash like this and applying .net updates usually fixed this, but I have not heard of this happening in Win10. 

Have you tried checking Windows Update to see if there are any pending updates for your machine? I cannot reproduce this issue on any machine that I have access to. Do you have any other machines where you can test DAX Studio?

**Comment by write2anees** [comment]
Below is what event viewer captured.

The program DaxStudio.exe version 2.12.2.344 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 393c
 Start Time: 01d67597746448ca
 Termination Time: 7
 Application Path: C:\Program Files\DAX Studio\DaxStudio.exe
 Report Id: e9e30c76-e18c-11ea-b1e8-10c37b1bed62
 Faulting package full name: 
 Faulting package-relative application ID: 

I did not find a problem history in Security and Maintenance.

**Comment by HappymediaDz** [comment]
> Is anyone experiencing the same problem?

Yes, I'm experiencing the same issue. It started with the preview update of DAX Studio, I was expecting that installing the latest version will solve the problem but it remains

**Comment by dgosbell** [comment]
@HappymediaDz  - which preview update are you talking about? Do you know an earlier version number that did work for you? 

I can't reproduce this issue on any of the machines I have access to. I don't know if it's caused by something in the DAX Studio code base itself or if it's in one of the third party controls we are using. Both the window docking framework and the ribbon are large complex projects.

Could you post the output from DaxStudio.Checker and the diagnostic logging so that I can compare the results to the output from write2anees to see if this is the same issue?

**Comment by ShelleySmith** [comment]
@dgosbell Hi Darren, Yes, I am having this same issue. I've tried installing for "all users" and just me and still the same results. The logo comes up when trying to run and it just spins, using a lot of resources as shown in the task manager.

**Comment by dgosbell** [comment]
@ShelleySmith - so when you say you are seeing the same issue are you saying that the diagnostic logging stops at the same point as the one uploaded by write2anees and that you are seeing the same event in the Windows Event viewer about DaxStudio.exe has stopped interacting? Has DAX Studio been working previously on this machine or is this a first time install?

I'm not able to reproduce this issue on any of the systems I have access to. I'm looking to add some more detail to the diagnostic logging to help isolate a bit more where this appears to be getting stuck.

**Comment by ShelleySmith** [comment]
@dgosbell I am saying the program appears to install, but when I try to run it, the logo appears, but the program never opens. When I go into task manager, it says the program is not responding. 

I'm really confident I had an old version on the old hard drive (Windows 7) on this machine, but I don't think I had it previously installed on my current hard drive (new hard drive) with Windows 10 on this machine, but I'm not 100% sure. (I could've installed and then never really used it and so forgot about it). I've tried installing and uninstalling multiple times and every time, the logo comes up, but the program doesn't run successfully. 

I uninstalled again, and then loaded an old version (I think 2.9 instead of 2.12) from our company software "store" and that version did install and does open, but it is the old version. The same thing happened to one of my co-workers in India. He is the one who told me to try it from our company store because that's the only thing that worked for him. He said when he tries to then upgrade this old version to the 2.12 version, it still doesn't work. I haven't tried it for myself yet.

**Comment by HappymediaDz** [comment]
> @HappymediaDz  - which preview update are you talking about? Do you know an earlier version number that did work for you?
> I can't reproduce this issue on any of the machines I have access to. I don't know if it's caused by something in the DAX Studio code base itself or if it's in one of the third party controls we are using. Both the window docking framework and the ribbon are large complex projects.
> Could you post the output from DaxStudio.Checker and the diagnostic logging so that I can compare the results to the output from write2anees to see if this is the same issue?

Hi @dgosbell ,
Sorry for the late reply but we are facing (in Algeria) Internet connexion problem

The problem appeared when I installed the version 2.10.2. I thought that a newer version will solve the problem but it is still existing with the version 2.12.2.

The last working version was the version 2.6.0 I uninstalled the 2.12.2 version and reinstall the 2.6.0 version and it works fine (unfortunately it is not supported with the external tool).

Bellow the output of the studio.cheker
======================

    Version =  v2.12.2.344
    DaxStudio.exe Version =  v2.12.2.344

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Entreprise
    OSRelease       = 1809
    OSVersion       = 10.0.17763
    OSArchitecture  = 64 bits
    VisibleMemoryGB = 15,89
    FreeMemoryGB    = 9,15

    Culture Name              = fr-FR
    Culture DisplayName       = Français (France)
    Culture EnglishName       = French (France)
    Culture 2-Letter ISO Name = fr
    Culture DecimalSeparator  = ,
    Culture GroupSeparator    = .
    Culture CurrencySymbol    = €
    Culture ShortDatePattern  = dd/MM/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
Display: \\.\DISPLAY2  
         X: 2400 Y: 0 Width: 2000 Height: 1125

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1036 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1036 -> 3.0.30729.8795
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1036 -> 3.5.30729.5003
    v4\Client -> 4.7.03190
    v4\Client\1033 -> 4.7.03190
    v4\Client\1036 -> 4.7.03190
    v4\Full -> 4.7.03190
    v4\Full\1033 -> 4.7.03190
    v4\Full\1036 -> 4.7.03190
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 461814 (4.7.2)
    PASS > .Net Version 4.7.2 is above the required minimum

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 21
    AMO : 19.6.0.0
    ADOMD : 19.6.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      **N/A  >  - ࠧ 
Générateur d'aperçu : Générateur d’aperçu Microsoft Exc**

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.12.2.344, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files (x86)\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4M_1036
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4R
        VSTORFeature_UNM 1
        VSTORFeature_CLR35 1
        VSTORFeature_CLR40 1
        Version 10.0.60724
        Revision 00
        ProductCode {7C0242A3-8B66-35D1-9FE0-13B426ACB609}
      v4R_1036
        VSTOR_res_UNM 1
        VSTOR_res_CLR35 1
        VSTOR_res_CLR40 1
        Version 10.0.60724
        ProductCode {F7A83723-0746-3DCA-A011-DEC81093E828}
      v4_1036
        Install 1

Registry Settings
=======================
    DaxFormatterRequestTimeout = 10
    EditorEnableIntellisense = True
    EditorFontFamily = Lucida Console
    EditorFontSize = 11
    EditorShowLineNumbers = True
    LastVersionCheckUTC = 2020-08-25T08:38:00
    ProxyAddress = 
    ProxyPassword = 
    ProxyUser = 
    ProxyUseSystem = True
    QueryEndEventTimeout = 5
    QueryHistoryMaxItems = 200
    QueryHistoryShowTraceColumns = True
    WindowPosition = ﻿<?xml version="1.0" encoding="utf-8"?><WINDOWPLACEMENT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><length>44</length><flags>0</flags><showCmd>1</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>64</Left><Top>6</Top><Right>1464</Right><Bottom>906</Bottom></normalPosition></WINDOWPLACEMENT>

**Comment by HappymediaDz** [comment]
I just saw that the DAX Studio Add-in for Excel does not activate with version 2.12.2. while it works fine with version 2.6.
For information I'm using the version 2007 of Excel (build 13029.20344)

**Comment by ellygirl084** [comment]
I've came accross this exact issue. All Windows 10 1607 had this behaviour. Upgrading the OS to Windows 10 1909 did the trick.

**Comment by ShelleySmith** [comment]
I'm on Windows 10 Enterprise version 1809.

**Comment by dgosbell** [comment]
Thanks for the suggestion @ellygirl084 . It might not be 1909 specifically that fixed this, but 1909 does come with .Net 4.8. My home machine is also on 1909, but work machine is still on 1803 however I do have .Net 4.8 on it. I did find this [blog post](https://weblog.west-wind.com/posts/2019/Feb/14/WPF-Hanging-in-Infinite-Rendering-Loop) which discusses a very similar scenario where a small percentage of people running .Net 4.7.x were seeing application hangs. 

So there are 3 things worth trying:

1. if any of you seeing this issue are using a display scale setting that is **not** 100% (right click on an empty portion of your desktop, go to **Display Settings** and check the setting under **Scale and layout**) - as a test could you try changing this to 100% temporarily and see if DAX Studio will start? If so you may be hitting the issue from the blog post above and it would be worth trying item 2 below.
2. In the folder where DAX Studio is installed is a file called `daxstudio.exe.config`. Copy this file out to your desktop or some other temporary location. Then open it in a text editor, about 14 lines down you will fine a line that says '<runtime>', add a line under that and insert the following '<AppContextSwitchOverrides value="Switch.System.Windows.Controls.Grid.StarDefinitionsCanExceedAvailableSpace=true" />'. Then copy this edited file back over the top of the original file. Then try launching DAX Studio.
3. Another option would be to try updating to .net 4.8 (which you can get from [https://dotnet.microsoft.com/download/dotnet-framework/net48](https://dotnet.microsoft.com/download/dotnet-framework/net48) ) 

I'd be interested to hear if any of the above helps resolve this issue.

> I just saw that the DAX Studio Add-in for Excel does not activate with version 2.12.2. while it works fine with version 2.6.
For information I'm using the version 2007 of Excel (build 13029.20344)

@HappymediaDz -  The Excel addin does not have any user interface components apart from the ribbon button so it's almost certainly not the same issue. But it can be impacted by other add-in. Do you have any other addins in your copy of Excel? If so can you try disabling them temporarily to see if DAX Studio loads?

**Comment by HappymediaDz** [comment]
I was able to solve the problem by installing the 4.8 version of .Net Framework I did not do any thing else.
Thank you @dgosbell  for your help and assistance and thanks to all for your contributions.

**Comment by write2anees** [comment]
Yeah, Installing .Net Framework 4.8 did the trick.
Thanks @dgosbell 
Thanks everyone for sharing your inputs.

**Comment by dgosbell** [comment]
Thanks for confirming that that DAX Studio is now working, it does sound like you may have hit that bug with .Net 4.7.1.

**Comment by ShelleySmith** [comment]
I ran the .NET 4.8 installation file, but it looks like my system is still only at .NET version 4.7 and latest version of DAX Studio still hangs up at the logo when I try to run it. I'm thinking there is some program that still uses 4.7 installed on my machine, but I don't know how to figure out which one. 

![Annotation 2020-08-31 095726](https://user-images.githubusercontent.com/44201781/91734373-7c26bf00-eb70-11ea-8cd7-c9d99e85aee0.png)

![Annotation 2020-08-31 2](https://user-images.githubusercontent.com/44201781/91734473-9791ca00-eb70-11ea-9d88-1592b5fefd07.png)

**Comment by ShelleySmith** [comment]
Okay @dgosbell - it didn't work at first, and after a couple hours, my machine came up with a message that my machine required restart for new software (I already did this myself a couple times). I restarted, tried DAX Studio and it comes up and runs version 2.12.2! Thanks for the help!

![image](https://user-images.githubusercontent.com/44201781/91766396-2407b100-eba0-11ea-8fb0-789bf6ebf7f8.png)

**Comment by Ayfarag102** [comment]
Hey everyone,
Kindly reopening this issue ticket for DaxStudio, dated today 22/09/2021 5:37 PM EST
I'm running on a Windows 10 Home Edition x64, and installed the application.
Sadly, not even the logo appears and the application doesn't start. I tried following what was mentioned on the [DaxStudio Checker](https://daxstudio.org/documentation/troubleshooting/daxstudio-checker/) page to check what could the problem be,  it starts off just showing the version and DaxStudio.exe version number then it barely passes the "**Checking Operating System**" logging showing a fatal error warning.

If I could please get some help, that would be great
