### ISSUE TITLE
I can not get Dax Studio to Install (Excel Add In)

### ISSUE THREAD

**Issue by AtlMichael** [DaxStudio/DaxStudio#55]
Looks like my prequisites are OK.  In Excel--->Options--->Add Ins--->Com Add Ins Dax Studio does not show up.  Here is the checker log:

    Version =  v2.7.4.102

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSVersion       = 10.0.14393
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.90
    FreeMemoryGB    = 11.13

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.7.02053
    v4\Client\1033 -> 4.7.02053
    v4\Full -> 4.7.02053
    v4\Full\1033 -> 4.7.02053
    v4.0\Client -> 4.0.0.0

Checking AMO
=======================
    PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 9
    AMO : 13.0.0.0
    ADOMD : 13.0.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excel_v16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.4.102, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64

FATAL ERROR:
Object reference not set to an instance of an object.
   at DaxStudio.Checker.Checker.CheckVSTO()
   at DaxStudio.Checker.Checker.CheckExcelAddin()
   at DaxStudio.Checker.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

**Comment by dgosbell** [comment]
I'm a bit worried about the fatal error in the CheckVSTO call, but I was pretty sure that PowerPivot was using VSTO (Visual Studio Tools for Office) internally, so if that works DAX Studio should work too.

Do you have the Power Pivot addin for Excel enabled? Can you see the Power Pivot ribbon and open the "Manage" window?

If PowerPivot is installed and working the next thing you could try is the following to see if that will give us a more detailed error message:

1. Close all copies of Excel 
2. Run DaxStudio.Checker, go to the File menu and click on "Enable VSTO Alerts"
3. Start Excel, hopefully this will display an error message about why DAX Studio is not loading
4. Paste the details of any error message back to this issue
5. Close Excel
6. From DaxStudio.Checker, go to the File menu and disable the "Enable VSTO Alerts" option

**Comment by AtlMichael** [comment]
Hello and thank you for the quick response.  I followed the instructions provided and Excel opened normally after changing DaxStudio.Checker to Enable VTSO alerts.  A few more details on the situation:  

1.  Yes, Power Pivot is installed and is running fine.  I can create models, Dax formulas process correctly, I can build Pivot Tables and Power View reports sourcing from the PP model.

2. When I installed Dax Studio a first time,  the App installed fine (I could see Dax Studio App in windows control panel/apps and open the "thick" Dax Studio app).  I did see the Dax Studio Add In in Excel, I activated it (or tired to) by clicking the checkbox for the Add In @ app path Excel--->Options--->Add Ins--->Com Add Ins, but the Dax Studio Icon would not show up in the "Add-Ins" Section of the Excel Ribbon.  Curiously, the Add-Ins ribbon was never visible before doing this, but still, the Dax Studio Icon on the Add Ins ribbon was not there.  So the install of Dax Studio clearly added the new ribbon section to my Excel but seem like it did not fully install

2.  At this point I unistalled and reinstall Dax Studio several times and got the same behavior as above

3. I ran DaxStudio.Checker and it showed an error for AMOMD.NET.  I got the MS update to ADOMD.NET.  Ran that update and reinstalled Dax Studio. I got the same behavior however the ADOMD.net error thrown by DaxStudio.Checker went away

4.  I then went back into the Excel Add Ins Manager section (Excel--->Options--->Add Ins--->Com Add Ins).  I once again clicked the checkbox next to the Dax Studio Add in in and clicked "Remove"

5. I uninstalled and reinstalled Dax Studio again and now I do not even see the Dax Studio Add In in the Excel Add Ins Manager section (Excel--->Options--->Add Ins--->Com Add Ins).  Its just not there at all.

**Comment by dgosbell** [comment]
Glad you got this working. It's a bit strange, because the Enable VSTO Alerts does not change anything in the way the DAX Studio addin operates, it's a developer option that tells Excel to show a message box if it hits an error while loading an addin (normally Excel will just silently disable an addin that throws an error while loading)

The normal flow of things should be that you install DAX Studio and the next time you start Excel the Addin ribbon is there and the DAX Studio button is visible. You should not have to manually do anything in the Excel Options. If Excel was running or if there was a hidden "crashed" copy of Excel it could maybe cause issues like this.  I think we've had one other person where a re-boot then a re-install fixed a strange issue like this.

**Comment by AtlMichael** [comment]
I was not able to get it to work

**Comment by dgosbell** [comment]
So did you close the issue by accident then?  

If DAX Studio is still not appearing in the Ribbon and you are not getting any errors maybe try uninstalling, then re-booting, then re-installing.

**Comment by AtlMichael** [comment]
If it was me that closed it, then yes.

**Comment by dgosbell** [comment]
@AtlMichael  - did you try re-installing?

**Comment by lfynmore** [comment]
Was this issue resolved? I am also experiencing this issue. I download DAX, open up Excel, no Add-in tab, then i go into Add-ins and try and force the option to show up - nothing! I cannot get the Add-in tab to show in Excel 2016 no matter what I do. I have tried re-installing, restarting - everything!

Id appreciate any help at all!

**Comment by lfynmore** [comment]
Thanks for you response.

Using Excel 2016 16.0.4639.1000 32 bit
Standalone version of DAX is working and opening fine, im not using any other Add-ins.

Something else worth mentioning, I am installing on a work computer which requires administrators permission to install. When we run excel as an administrator, the addins ribbon will show up and DAX will be there. However, as I am not an administrator, I cannot run excel as administrator.

We tried installing it using the IT departments administrator username and password, and they also granted me temporary administrator rights so I could install it using my username and password in case this was the issue. None of these solutions worked and I was still unable to get my Addins ribbon to show when I try and run Excel normally.

My colleague has the same version of excel as I do, and has been using DAX for a few years and has not experienced the same issue as me.

**Comment by dgosbell** [comment]
You should only need admin rights to install DAX Studio and that is just because we install to "c:\program files" and register the addin at the machine level. But after install you do not need to run Excel as Admin.

Can you try running [DAX Studio Checker](http://daxstudio.org/documentation/troubleshooting/daxstudio-checker/) and post the output here so that I can see if that gives us any hints as to what may be going on.

**Comment by lfynmore** [comment]
Version =  v2.7.4.102

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSVersion       = 10.0.14393
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 7.86
    FreeMemoryGB    = 5.07

    Culture Name              = en-AU
    Culture DisplayName       = English (Australia)
    Culture EnglishName       = English (Australia)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = d/MM/yyyy

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.6.01586
    v4\Client\1033 -> 4.6.01586
    v4\Full -> 4.6.01586
    v4\Full\1033 -> 4.6.01586
    v4.0\Client -> 4.0.0.0

Checking AMO
=======================
    PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91

Checking ADOMD.NET
=======================
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 9
    AMO : 13.0.0.0
    ADOMD : 13.0.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excel_v16
    Excel Path: C:\PROGRA~2\MICROS~2\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.4.102, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60301
        Install 1
        InstallerPath C:\Program Files (x86)\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR40 1

**Comment by dgosbell** [comment]
OK, so the DAX Studio Checker output looks fine, I can't see any signs of any of the known issues which might cause the Excel add-in to not load.

Can you right click on the ribbon in Excel and choose the option to "Customize Ribbon" and make sure that the Add-ins tab has a tick next to it to ensure it is visible and looks like the image below?
![image](https://user-images.githubusercontent.com/8241830/40716869-b91adad8-644d-11e8-9e89-01aae10c967f.png)

If your Addins tab is already set to visible can you open a Windows Explorer window and navigate to %APPDATA%\DaxStudio\log and see if there are any files starting with DaxStudioExcel-YYYYMMDD.txt and if there are can you upload the most recent one?

**Comment by dgosbell** [comment]
If you want to include files and images I think you'll need to go to the issue on GitHub and add them there. Replying to the notification email strips out everything except the text.

**Comment by lfynmore** [comment]
I have checked the Customize Ribbon section. The addin is ticked, however I have no DAX studio in there.

Also, I went to '%APPDATA%\DaxStudio\log' and there were no files starting with DaxStudioExcel-yyyymmdd

**Comment by dgosbell** [comment]
OK, so that means that Excel has not loaded the addin which is strange because the information in the DAX Studio Checker output indicates that the add-in is registered correctly and is not listed in the disabled addins. If the addin is not loaded I would not expect any log files.

In an earlier comment you mentioned that you had a screen capture of an error, but it got stripped out of your reply. Can you upload that screen shot onto this issue [on github](https://github.com/DaxStudio/DaxStudio/issues/55)

**Comment by lfynmore** [comment]
Sorry, that wasn't me. No error has come up at all. Ive not even been able to get it to load to give me an error at this point.

**Comment by lfynmore** [comment]
Just wanting to double check, could the issue be that I am running 32 bit excel? Although my colleague has version 2.6 and the same set up as I do and has no issues with getting it to load...

**Comment by dgosbell** [comment]
Oops sorry, I think that other guy responded to the wrong issue :)

I don't really know why your Excel is not loading the addin, your system does not appear to have any of the known issues which have caused failures in the past with the addin loading (and as we find any of these we try to build fixes into the installer anyway)

The other thing we could try is enabling VSTO alerts (see the bottom of [this page](http://daxstudio.org/documentation/troubleshooting/daxstudio-checker/) ). VSTO is the Microsoft framework that the DAX Studio addin is built using. If Excel is throwing an error while attempting to load the addin this should force it to display. You'll need to shutdown all copies of Excel, then enable this setting, then startup Excel. (you can then go back into DAX Studio Checker and disable this setting again)

If Excel displays an error message can you post the text or a screen shot here?

If it does not display an error then something else is blocking the addin from loading. Do you have a 3rd party Anti-Virus scanner of some sort?

**Comment by dgosbell** [comment]
> Just wanting to double check, could the issue be that I am running 32 bit excel? Although my colleague has version 2.6 and the same set up as I do and has no issues with getting it to load...

No, it should not matter. We do primarily develop and test using 64bit Excel, but the addin is tested and works for both 32 and 64 bit versions of Excel and Windows. (so we've tested 32bit Excel on 32bit Windows and 32bit Excel on 64bit Windows and 64bit Excel on 64bit windows..)

**Comment by lfynmore** [comment]
No error message came up at all when I enabled VSTO alerts.

No third party Anti-Virus. Looks like its just Windows Defender.

**Comment by dgosbell** [comment]
I'm not really sure what else to check now. You could maybe try running a repair on your copy of Office...

You have all the correct dependencies, the addin is correctly registered and not in the disabled list. I can't see any logical reason why the addin is not loading. My only guess at the moment is that there is some corruption or configuration issue with your copy of Excel.

**Comment by therealsteveross** [comment]
I couldn't connect Excel Power Pivot models to DAX Studio.  Yes, with Power BI, but no success with Excel 2016.  I could see that the DAX Studio Excel Add-in was "inactive".  In Excel, File/Options/Add-ins/Manage/Comm Add-ins/Go.  Check the Dax Studio Excel Add-in to make it an active add-in.  Now works perfectly.

**Comment by dgosbell** [comment]
We've just released v2.8.1 if you want to see if that is any better? We did not really change the Excel Addin though so it's a bit of a long shot.

**Comment by therealsteveross** [comment]
It works for me if I connect DAX Sudio to the Excel file from the Excel Add-Ins menu.  If I open DAX Studio independently, it will not connect to the Excel file.
![dax studio to excel](https://user-images.githubusercontent.com/42361537/51613625-78897b80-1ee9-11e9-8e07-bddfaccd9296.JPG)

**Comment by dgosbell** [comment]
> It works for me if I connect DAX Sudio to the Excel file from the Excel Add-Ins menu. If I open DAX Studio independently, it will not connect to the Excel file.
Yes, that's how it works. It is impossible to connect to a data model running inside Excel unless your code is also running inside Excel. 
Thats why we added the help icon with the foillowing tooltip when you launch DAX Studio outside of Excel 
![image](https://user-images.githubusercontent.com/8241830/51633226-49384480-1fa5-11e9-92a4-3a7f57122e6c.png)

**Comment by claudiohm** [comment]
Hello. I have the same problem. I installed Analysis Services, and the problem remained.
The additional software needed was the VSTO Runtime. 
Now it works!!!
Hope it helps
Regards

**Comment by dgosbell** [comment]
Hmm, the installer specifically checks for the VSTO Runtime and should attempt to download and install it if it's not present so I'm not sure what blocked this on your machine. Good to hear that it's now working

**Comment by RamonBarrull** [comment]
To solve the problem try to execute the file:
C:\Program Files\DAX Studio\bin\DaxStudio.vsto
After go to complements an activate the dax studio addin, is possible that apperars 2 instances of dax studio addin.
the good one is:
file:///C:\Program Files\DAX Studio\bin\DaxStudio.vsto|vstolocal

Now is working for me.

It's possible that you need to delete and reinstall dax studio. and restart the computer

I hope that solve your problem

;)

**Comment by dbmats** [comment]
I deleted the Dax studio add-in and this program. I thought that when I needed it, I would install and connect it again. But when connecting, the above problems occurred. Nothing helped. But I have Office 365, I updated it and everything worked.

**Comment by andreadinisio** [comment]
I got the same issue. This is the error from vsto Alert. How can I solve it?

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: 
    Excel Architecture: Unknown

      ERROR: Unsupported Excel Architecture Unknown
    DAX Studio Excel Add-in Registry keys
       Description: DAX Studio Excel Add-In
       FriendlyName: DAX Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - https://mbsconsulting.sharepoint.com/sites/2022_creditagricole_modificheunilaterali/documenti%20condivisi/3.%20inflazione/1.%20analisi/7.%20file%20di%20test/20220830%20-%20ca%20-%20inflazione%20-%20test%20v1.xl

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=3.0.0.725, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4M_1040
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
